version: '3.8'

services:
  mongo:
      image: mongo
      restart: always
      expose:
        - 27017

      ports:
        - 27017:27017

  backend:
    build: ./backend/

    ports:
      - 8080:8080

    depends_on:
      - mongo
  
  frontend:
    build: ./frontend

    ports:
      - 3000:3000